import { AiFillStar } from "react-icons/ai";

const data = [
  {
    id:1,
    imageUrl: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    name: "Nike Air Monarch IV",
    star: <AiFillStar className="rating-star" />,
    reviews: "(116 reviews)",
    price: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
    site: "amazon"
  },
  {
    id:2,
    imageUrl: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    name: "Nike Air Vapormax Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "200",
    company: "Nike",
    color: "red",
    category: "sneakers",
    site: "flipkart"
  }, 
  {
    id:3,
    imageUrl: "https://m.media-amazon.com/images/I/71v2jVh6nIL._SL1500_.jpg",
    name: "Apple iPhone 15 (128 GB)",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "70,999",
    company: "Apple",
    color: "Pink",
    category: "electronics",
    site: "amazon"
  },

  {
    id:4,
    imageUrl: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
    name: "Nike Waffle One Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
    site: "ajio",
    tracking: "True"
  },
  {
    id:5,
    imageUrl: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    name: "Nike Running Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "200",
    company: "Adidas",
    color: "black",
    category: "sneakers",
    site: "ajio",
    tracking: "True"
  },
  {
    id:6,
    imageUrl: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
    name: "Flat Slip On Pumps",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "200",
    company: "Vans",
    color: "green",
    category: "flats",
    site: "amazon",
    tracking: "True"
  },
  {
    id:7,
    imageUrl: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
    name: "Knit Ballet Flat",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "50",
    company: "Adidas",
    color: "black",
    category: "flats",
  },

  {
    id:8,
    imageUrl: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    name: "Loafer Flats",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "50",
    company: "Vans",
    color: "white",
    category: "flats",
    site: "amazon"
  },

  {
    id:9,    
    imageUrl: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    name: "Nike Zoom Freak",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
    site: "indiamart"
  },

  {
    id:10,
    imageUrl: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    name: "Nike Men's Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "200",
    company: "Adidas",
    color: "blue",
    category: "sneakers",
    site: "indiamart"

  },

  {
    imageUrl: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    name: "PUMA BLACK-OCE",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "150",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    imageUrl: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    name: "Pacer Future Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "150",
    company: "Puma",
    color: "red",
    category: "sneakers",
    tracking: "True"
  },
  {
    imageUrl: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    name: "Unisex-Adult Super",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },
  {
    imageUrl: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    name: "Roma Basic Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "150",
    company: "Puma",
    color: "white",
    category: "sneakers",
    tracking: "True",
  },
  {
    imageUrl: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    name: "Pacer Future Doubleknit",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
    tracking: "True"
  },

  {
    imageUrl: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    name: "Fusion Evo Golf Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "100",
    company: "Puma",
    color: "green",
    category: "sneakers",
    tracking: "True"
  },
  {
    imageUrl: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    name: "Rainbow Chex Skate",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "100",
    company: "Vans",
    color: "red",
    category: "flats",
  },
  {
    imageUrl: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    name: "Low-Top Trainers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "100",
    company: "Vans",
    color: "white",
    category: "sandals",
  },
  {
    imageUrl: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    name: "Vans Unisex Low-Top",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "100",
    company: "Vans",
    color: "blue",
    category: "sandals",
  },
  {
    imageUrl: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    name: "Classic Bandana Sneakers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "50",
    company: "Nike",
    color: "black",
    category: "sandals",
  },
  {
    imageUrl: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    name: "Chunky High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "50",
    company: "Vans",
    color: "black",
    category: "heels",
  },
  {
    imageUrl: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
    name: "Slip On Stiletto High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "100",
    company: "puma",
    color: "black",
    category: "heels",
  },
  {
    imageUrl: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    name: "DREAM PAIRS Court Shoes",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "150",
    company: "Nike",
    color: "red",
    category: "heels",
  },
  {
    imageUrl: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    name: "Nike Air Vapormax Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "200",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },

  {
    imageUrl: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
    name: "Low Mid Block Heels",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "200",
    company: "Nike",
    color: "black",
    category: "heels",
  },
  {
    imageUrl: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
    name: "Chunky High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "50",
    company: "Adidas",
    color: "black",
    category: "heels",
  },
  {
    imageUrl: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
    name: "Amore Fashion Stilettos",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "150",
    company: "Adidas",
    color: "white",
    category: "heels",
  },
  {
    imageUrl: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
    name: "Bridal Sandals Glitter",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "50",
    company: "Adidas",
    color: "black",
    category: "heels",
  },
  {
    imageUrl: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
    name: "Wedding Prom Bridal",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "50",
    company: "Adidas",
    color: "black",
    category: "flats",
  },

];

export default data;
